# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:04
# flake8: noqa
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotFoundEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('redirect_to', models.CharField(blank=True, max_length=512, null=True)),
                ('permanent', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_found_entries', to='sites.Site')),
            ],
        ),
    ]
